apiVersion: v1
kind: Service
metadata:
  name: eihu-nodejs-app-service
  namespace: eihu
spec:
  type: NodePort
  selector:
    app: eihu-nodejs-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32005
